---
- hosts: all
  become: true
  vars:
      ansible_python_interpreter: /usr/bin/python3
  tasks:


  - name: install python3 and pip in Ubuntu
    apt:
      name:
        - python3
      state: latest
    when: ansible_distribution == "Ubuntu"

  - name: install python3 and pip in CentOS
    dnf:
      name:
        - python3
      state: latest
    when: ansible_distribution == "CentOS"

  - name: install and upgrade pip in Ubuntu 
    pip:
      name: pip
      extra_args: --upgrade
      executable: pip3
    when: ansible_distribution == "Ubuntu" 

  - name: install and upgrade pip in CentOS 
    pip:
      name: pip
      extra_args: --upgrade
      executable: pip3
    when: ansible_distribution == "CentOS" 

  - name: install Java OpenJDK in Ubuntu
    apt:
      name: openjdk-11-jdk
      state: latest
    when: ansible_distribution == "Ubuntu"


  - name: install Java OpenJDK in CentOS    
    dnf:
      name: java-11-openjdk-devel
      state: latest
    when: ansible_distribution == "CentOS"




